// SpaceTraders v2.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.2
// source: api_systems.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetJumpGateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *JumpGate `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetJumpGateResponse) Reset() {
	*x = GetJumpGateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_systems_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJumpGateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJumpGateResponse) ProtoMessage() {}

func (x *GetJumpGateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_systems_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJumpGateResponse.ProtoReflect.Descriptor instead.
func (*GetJumpGateResponse) Descriptor() ([]byte, []int) {
	return file_api_systems_proto_rawDescGZIP(), []int{0}
}

func (x *GetJumpGateResponse) GetData() *JumpGate {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetMarketResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Market `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetMarketResponse) Reset() {
	*x = GetMarketResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_systems_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMarketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketResponse) ProtoMessage() {}

func (x *GetMarketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_systems_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketResponse.ProtoReflect.Descriptor instead.
func (*GetMarketResponse) Descriptor() ([]byte, []int) {
	return file_api_systems_proto_rawDescGZIP(), []int{1}
}

func (x *GetMarketResponse) GetData() *Market {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetShipyardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Shipyard `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetShipyardResponse) Reset() {
	*x = GetShipyardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_systems_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShipyardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipyardResponse) ProtoMessage() {}

func (x *GetShipyardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_systems_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipyardResponse.ProtoReflect.Descriptor instead.
func (*GetShipyardResponse) Descriptor() ([]byte, []int) {
	return file_api_systems_proto_rawDescGZIP(), []int{2}
}

func (x *GetShipyardResponse) GetData() *Shipyard {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetSystemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *System `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetSystemResponse) Reset() {
	*x = GetSystemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_systems_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSystemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemResponse) ProtoMessage() {}

func (x *GetSystemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_systems_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemResponse.ProtoReflect.Descriptor instead.
func (*GetSystemResponse) Descriptor() ([]byte, []int) {
	return file_api_systems_proto_rawDescGZIP(), []int{3}
}

func (x *GetSystemResponse) GetData() *System {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetWaypointResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Waypoint `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetWaypointResponse) Reset() {
	*x = GetWaypointResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_systems_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWaypointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWaypointResponse) ProtoMessage() {}

func (x *GetWaypointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_systems_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWaypointResponse.ProtoReflect.Descriptor instead.
func (*GetWaypointResponse) Descriptor() ([]byte, []int) {
	return file_api_systems_proto_rawDescGZIP(), []int{4}
}

func (x *GetWaypointResponse) GetData() *Waypoint {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListSystemsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*System `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Meta *Meta     `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
}

func (x *ListSystemsResponse) Reset() {
	*x = ListSystemsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_systems_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSystemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSystemsResponse) ProtoMessage() {}

func (x *ListSystemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_systems_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSystemsResponse.ProtoReflect.Descriptor instead.
func (*ListSystemsResponse) Descriptor() ([]byte, []int) {
	return file_api_systems_proto_rawDescGZIP(), []int{5}
}

func (x *ListSystemsResponse) GetData() []*System {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListSystemsResponse) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type ListWaypointsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Waypoint `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Meta *Meta       `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
}

func (x *ListWaypointsResponse) Reset() {
	*x = ListWaypointsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_systems_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWaypointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWaypointsResponse) ProtoMessage() {}

func (x *ListWaypointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_systems_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWaypointsResponse.ProtoReflect.Descriptor instead.
func (*ListWaypointsResponse) Descriptor() ([]byte, []int) {
	return file_api_systems_proto_rawDescGZIP(), []int{6}
}

func (x *ListWaypointsResponse) GetData() []*Waypoint {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListWaypointsResponse) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_api_systems_proto protoreflect.FileDescriptor

var file_api_systems_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x70, 0x69, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x6d, 0x61, 0x63, 0x67, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x2e, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x1a,
	0x0f, 0x6a, 0x75, 0x6d, 0x70, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x0c, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a,
	0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x73, 0x68, 0x69, 0x70,
	0x79, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x73, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x77, 0x61, 0x79, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4f, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4a,
	0x75, 0x6d, 0x70, 0x47, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x38, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e,
	0x6d, 0x61, 0x63, 0x67, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74,
	0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4a, 0x75, 0x6d, 0x70, 0x47,
	0x61, 0x74, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x4b, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6d,
	0x61, 0x63, 0x67, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x72,
	0x61, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x4f, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x53, 0x68, 0x69,
	0x70, 0x79, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6d, 0x61,
	0x63, 0x67, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61,
	0x64, 0x65, 0x72, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x68, 0x69, 0x70, 0x79, 0x61, 0x72,
	0x64, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x4b, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6d, 0x61, 0x63,
	0x67, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64,
	0x65, 0x72, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x4f, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x57, 0x61, 0x79, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6d, 0x61, 0x63, 0x67,
	0x65, 0x6e, 0x69, 0x75, 0x73, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65,
	0x72, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x57, 0x61, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x83, 0x01, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6d, 0x61,
	0x63, 0x67, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61,
	0x64, 0x65, 0x72, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x34, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6d, 0x61, 0x63, 0x67, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x2e,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x22, 0x87, 0x01, 0x0a, 0x15,
	0x4c, 0x69, 0x73, 0x74, 0x57, 0x61, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6d, 0x61, 0x63, 0x67, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x2e,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x57, 0x61, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x34, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e,
	0x6d, 0x61, 0x63, 0x67, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74,
	0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52,
	0x04, 0x6d, 0x65, 0x74, 0x61, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x2f, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_systems_proto_rawDescOnce sync.Once
	file_api_systems_proto_rawDescData = file_api_systems_proto_rawDesc
)

func file_api_systems_proto_rawDescGZIP() []byte {
	file_api_systems_proto_rawDescOnce.Do(func() {
		file_api_systems_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_systems_proto_rawDescData)
	})
	return file_api_systems_proto_rawDescData
}

var file_api_systems_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_systems_proto_goTypes = []interface{}{
	(*GetJumpGateResponse)(nil),   // 0: macgenius.spacetraders.api.GetJumpGateResponse
	(*GetMarketResponse)(nil),     // 1: macgenius.spacetraders.api.GetMarketResponse
	(*GetShipyardResponse)(nil),   // 2: macgenius.spacetraders.api.GetShipyardResponse
	(*GetSystemResponse)(nil),     // 3: macgenius.spacetraders.api.GetSystemResponse
	(*GetWaypointResponse)(nil),   // 4: macgenius.spacetraders.api.GetWaypointResponse
	(*ListSystemsResponse)(nil),   // 5: macgenius.spacetraders.api.ListSystemsResponse
	(*ListWaypointsResponse)(nil), // 6: macgenius.spacetraders.api.ListWaypointsResponse
	(*JumpGate)(nil),              // 7: macgenius.spacetraders.api.JumpGate
	(*Market)(nil),                // 8: macgenius.spacetraders.api.Market
	(*Shipyard)(nil),              // 9: macgenius.spacetraders.api.Shipyard
	(*System)(nil),                // 10: macgenius.spacetraders.api.System
	(*Waypoint)(nil),              // 11: macgenius.spacetraders.api.Waypoint
	(*Meta)(nil),                  // 12: macgenius.spacetraders.api.Meta
}
var file_api_systems_proto_depIdxs = []int32{
	7,  // 0: macgenius.spacetraders.api.GetJumpGateResponse.data:type_name -> macgenius.spacetraders.api.JumpGate
	8,  // 1: macgenius.spacetraders.api.GetMarketResponse.data:type_name -> macgenius.spacetraders.api.Market
	9,  // 2: macgenius.spacetraders.api.GetShipyardResponse.data:type_name -> macgenius.spacetraders.api.Shipyard
	10, // 3: macgenius.spacetraders.api.GetSystemResponse.data:type_name -> macgenius.spacetraders.api.System
	11, // 4: macgenius.spacetraders.api.GetWaypointResponse.data:type_name -> macgenius.spacetraders.api.Waypoint
	10, // 5: macgenius.spacetraders.api.ListSystemsResponse.data:type_name -> macgenius.spacetraders.api.System
	12, // 6: macgenius.spacetraders.api.ListSystemsResponse.meta:type_name -> macgenius.spacetraders.api.Meta
	11, // 7: macgenius.spacetraders.api.ListWaypointsResponse.data:type_name -> macgenius.spacetraders.api.Waypoint
	12, // 8: macgenius.spacetraders.api.ListWaypointsResponse.meta:type_name -> macgenius.spacetraders.api.Meta
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_systems_proto_init() }
func file_api_systems_proto_init() {
	if File_api_systems_proto != nil {
		return
	}
	file_jump_gate_proto_init()
	file_market_proto_init()
	file_meta_proto_init()
	file_shipyard_proto_init()
	file_system_proto_init()
	file_waypoint_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_systems_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJumpGateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_systems_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMarketResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_systems_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShipyardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_systems_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSystemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_systems_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWaypointResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_systems_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSystemsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_systems_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWaypointsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_systems_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_systems_proto_goTypes,
		DependencyIndexes: file_api_systems_proto_depIdxs,
		MessageInfos:      file_api_systems_proto_msgTypes,
	}.Build()
	File_api_systems_proto = out.File
	file_api_systems_proto_rawDesc = nil
	file_api_systems_proto_goTypes = nil
	file_api_systems_proto_depIdxs = nil
}
