// SpaceTraders v2.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.2
// source: api_contracts.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AcceptContractResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *AcceptContractResponse_Data `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *AcceptContractResponse) Reset() {
	*x = AcceptContractResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_contracts_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptContractResponse) ProtoMessage() {}

func (x *AcceptContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_contracts_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptContractResponse.ProtoReflect.Descriptor instead.
func (*AcceptContractResponse) Descriptor() ([]byte, []int) {
	return file_api_contracts_proto_rawDescGZIP(), []int{0}
}

func (x *AcceptContractResponse) GetData() *AcceptContractResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeliverContractRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShipSymbol  string `protobuf:"bytes,1,opt,name=ship_symbol,json=shipSymbol,proto3" json:"ship_symbol,omitempty"`
	TradeSymbol string `protobuf:"bytes,2,opt,name=trade_symbol,json=tradeSymbol,proto3" json:"trade_symbol,omitempty"`
	Units       int32  `protobuf:"varint,3,opt,name=units,proto3" json:"units,omitempty"`
}

func (x *DeliverContractRequest) Reset() {
	*x = DeliverContractRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_contracts_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliverContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverContractRequest) ProtoMessage() {}

func (x *DeliverContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_contracts_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverContractRequest.ProtoReflect.Descriptor instead.
func (*DeliverContractRequest) Descriptor() ([]byte, []int) {
	return file_api_contracts_proto_rawDescGZIP(), []int{1}
}

func (x *DeliverContractRequest) GetShipSymbol() string {
	if x != nil {
		return x.ShipSymbol
	}
	return ""
}

func (x *DeliverContractRequest) GetTradeSymbol() string {
	if x != nil {
		return x.TradeSymbol
	}
	return ""
}

func (x *DeliverContractRequest) GetUnits() int32 {
	if x != nil {
		return x.Units
	}
	return 0
}

type DeliverContractResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *DeliverContractResponse_Data `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DeliverContractResponse) Reset() {
	*x = DeliverContractResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_contracts_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliverContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverContractResponse) ProtoMessage() {}

func (x *DeliverContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_contracts_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverContractResponse.ProtoReflect.Descriptor instead.
func (*DeliverContractResponse) Descriptor() ([]byte, []int) {
	return file_api_contracts_proto_rawDescGZIP(), []int{2}
}

func (x *DeliverContractResponse) GetData() *DeliverContractResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type FulFillContractResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *FulFillContractResponse_Data `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *FulFillContractResponse) Reset() {
	*x = FulFillContractResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_contracts_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FulFillContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FulFillContractResponse) ProtoMessage() {}

func (x *FulFillContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_contracts_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FulFillContractResponse.ProtoReflect.Descriptor instead.
func (*FulFillContractResponse) Descriptor() ([]byte, []int) {
	return file_api_contracts_proto_rawDescGZIP(), []int{3}
}

func (x *FulFillContractResponse) GetData() *FulFillContractResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetContractResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Contract `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetContractResponse) Reset() {
	*x = GetContractResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_contracts_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractResponse) ProtoMessage() {}

func (x *GetContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_contracts_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractResponse.ProtoReflect.Descriptor instead.
func (*GetContractResponse) Descriptor() ([]byte, []int) {
	return file_api_contracts_proto_rawDescGZIP(), []int{4}
}

func (x *GetContractResponse) GetData() *Contract {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListContractsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Contract `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Meta *Meta       `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
}

func (x *ListContractsResponse) Reset() {
	*x = ListContractsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_contracts_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListContractsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContractsResponse) ProtoMessage() {}

func (x *ListContractsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_contracts_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContractsResponse.ProtoReflect.Descriptor instead.
func (*ListContractsResponse) Descriptor() ([]byte, []int) {
	return file_api_contracts_proto_rawDescGZIP(), []int{5}
}

func (x *ListContractsResponse) GetData() []*Contract {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListContractsResponse) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type AcceptContractResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Agent    *Agent    `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	Contract *Contract `protobuf:"bytes,2,opt,name=contract,proto3" json:"contract,omitempty"`
}

func (x *AcceptContractResponse_Data) Reset() {
	*x = AcceptContractResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_contracts_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptContractResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptContractResponse_Data) ProtoMessage() {}

func (x *AcceptContractResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_contracts_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptContractResponse_Data.ProtoReflect.Descriptor instead.
func (*AcceptContractResponse_Data) Descriptor() ([]byte, []int) {
	return file_api_contracts_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AcceptContractResponse_Data) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *AcceptContractResponse_Data) GetContract() *Contract {
	if x != nil {
		return x.Contract
	}
	return nil
}

type DeliverContractResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Contract *Contract  `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	Cargo    *ShipCargo `protobuf:"bytes,2,opt,name=cargo,proto3" json:"cargo,omitempty"`
}

func (x *DeliverContractResponse_Data) Reset() {
	*x = DeliverContractResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_contracts_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliverContractResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverContractResponse_Data) ProtoMessage() {}

func (x *DeliverContractResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_contracts_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverContractResponse_Data.ProtoReflect.Descriptor instead.
func (*DeliverContractResponse_Data) Descriptor() ([]byte, []int) {
	return file_api_contracts_proto_rawDescGZIP(), []int{2, 0}
}

func (x *DeliverContractResponse_Data) GetContract() *Contract {
	if x != nil {
		return x.Contract
	}
	return nil
}

func (x *DeliverContractResponse_Data) GetCargo() *ShipCargo {
	if x != nil {
		return x.Cargo
	}
	return nil
}

type FulFillContractResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Agent    *Agent    `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	Contract *Contract `protobuf:"bytes,2,opt,name=contract,proto3" json:"contract,omitempty"`
}

func (x *FulFillContractResponse_Data) Reset() {
	*x = FulFillContractResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_contracts_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FulFillContractResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FulFillContractResponse_Data) ProtoMessage() {}

func (x *FulFillContractResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_contracts_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FulFillContractResponse_Data.ProtoReflect.Descriptor instead.
func (*FulFillContractResponse_Data) Descriptor() ([]byte, []int) {
	return file_api_contracts_proto_rawDescGZIP(), []int{3, 0}
}

func (x *FulFillContractResponse_Data) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *FulFillContractResponse_Data) GetContract() *Contract {
	if x != nil {
		return x.Contract
	}
	return nil
}

var File_api_contracts_proto protoreflect.FileDescriptor

var file_api_contracts_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x70, 0x69, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x6d, 0x61, 0x63, 0x67, 0x65, 0x6e, 0x69, 0x75, 0x73,
	0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x61, 0x70,
	0x69, 0x1a, 0x0b, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a,
	0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x73, 0x68, 0x69, 0x70,
	0x5f, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe9, 0x01, 0x0a,
	0x16, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x6d, 0x61, 0x63, 0x67, 0x65, 0x6e, 0x69, 0x75,
	0x73, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x1a, 0x81, 0x01, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x37, 0x0a,
	0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6d,
	0x61, 0x63, 0x67, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x72,
	0x61, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52,
	0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x40, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6d, 0x61, 0x63, 0x67, 0x65,
	0x6e, 0x69, 0x75, 0x73, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x08,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x22, 0x72, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x69,
	0x76, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x68, 0x69, 0x70, 0x5f, 0x73, 0x79, 0x6d, 0x62, 0x6f,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x68, 0x69, 0x70, 0x53, 0x79, 0x6d,
	0x62, 0x6f, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x73, 0x79, 0x6d,
	0x62, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x64, 0x65,
	0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x22, 0xef, 0x01, 0x0a,
	0x17, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x38, 0x2e, 0x6d, 0x61, 0x63, 0x67, 0x65, 0x6e, 0x69,
	0x75, 0x73, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x85, 0x01, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x40, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x24, 0x2e, 0x6d, 0x61, 0x63, 0x67, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x2e, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x12, 0x3b, 0x0a, 0x05, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x25, 0x2e, 0x6d, 0x61, 0x63, 0x67, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x2e, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x68,
	0x69, 0x70, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x52, 0x05, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x22, 0xeb,
	0x01, 0x0a, 0x17, 0x46, 0x75, 0x6c, 0x46, 0x69, 0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x38, 0x2e, 0x6d, 0x61, 0x63, 0x67, 0x65,
	0x6e, 0x69, 0x75, 0x73, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x75, 0x6c, 0x46, 0x69, 0x6c, 0x6c, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x81, 0x01, 0x0a, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x37, 0x0a, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x21, 0x2e, 0x6d, 0x61, 0x63, 0x67, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x2e, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x52, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x40, 0x0a, 0x08, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6d,
	0x61, 0x63, 0x67, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x72,
	0x61, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x22, 0x4f, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x24, 0x2e, 0x6d, 0x61, 0x63, 0x67, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x2e, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x87, 0x01,
	0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6d, 0x61, 0x63, 0x67, 0x65, 0x6e, 0x69, 0x75,
	0x73, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x34, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x6d, 0x61, 0x63, 0x67, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x2e, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x65, 0x74,
	0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x69, 0x75, 0x73,
	0x2f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x70,
	0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_contracts_proto_rawDescOnce sync.Once
	file_api_contracts_proto_rawDescData = file_api_contracts_proto_rawDesc
)

func file_api_contracts_proto_rawDescGZIP() []byte {
	file_api_contracts_proto_rawDescOnce.Do(func() {
		file_api_contracts_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_contracts_proto_rawDescData)
	})
	return file_api_contracts_proto_rawDescData
}

var file_api_contracts_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_contracts_proto_goTypes = []interface{}{
	(*AcceptContractResponse)(nil),       // 0: macgenius.spacetraders.api.AcceptContractResponse
	(*DeliverContractRequest)(nil),       // 1: macgenius.spacetraders.api.DeliverContractRequest
	(*DeliverContractResponse)(nil),      // 2: macgenius.spacetraders.api.DeliverContractResponse
	(*FulFillContractResponse)(nil),      // 3: macgenius.spacetraders.api.FulFillContractResponse
	(*GetContractResponse)(nil),          // 4: macgenius.spacetraders.api.GetContractResponse
	(*ListContractsResponse)(nil),        // 5: macgenius.spacetraders.api.ListContractsResponse
	(*AcceptContractResponse_Data)(nil),  // 6: macgenius.spacetraders.api.AcceptContractResponse.Data
	(*DeliverContractResponse_Data)(nil), // 7: macgenius.spacetraders.api.DeliverContractResponse.Data
	(*FulFillContractResponse_Data)(nil), // 8: macgenius.spacetraders.api.FulFillContractResponse.Data
	(*Contract)(nil),                     // 9: macgenius.spacetraders.api.Contract
	(*Meta)(nil),                         // 10: macgenius.spacetraders.api.Meta
	(*Agent)(nil),                        // 11: macgenius.spacetraders.api.Agent
	(*ShipCargo)(nil),                    // 12: macgenius.spacetraders.api.ShipCargo
}
var file_api_contracts_proto_depIdxs = []int32{
	6,  // 0: macgenius.spacetraders.api.AcceptContractResponse.data:type_name -> macgenius.spacetraders.api.AcceptContractResponse.Data
	7,  // 1: macgenius.spacetraders.api.DeliverContractResponse.data:type_name -> macgenius.spacetraders.api.DeliverContractResponse.Data
	8,  // 2: macgenius.spacetraders.api.FulFillContractResponse.data:type_name -> macgenius.spacetraders.api.FulFillContractResponse.Data
	9,  // 3: macgenius.spacetraders.api.GetContractResponse.data:type_name -> macgenius.spacetraders.api.Contract
	9,  // 4: macgenius.spacetraders.api.ListContractsResponse.data:type_name -> macgenius.spacetraders.api.Contract
	10, // 5: macgenius.spacetraders.api.ListContractsResponse.meta:type_name -> macgenius.spacetraders.api.Meta
	11, // 6: macgenius.spacetraders.api.AcceptContractResponse.Data.agent:type_name -> macgenius.spacetraders.api.Agent
	9,  // 7: macgenius.spacetraders.api.AcceptContractResponse.Data.contract:type_name -> macgenius.spacetraders.api.Contract
	9,  // 8: macgenius.spacetraders.api.DeliverContractResponse.Data.contract:type_name -> macgenius.spacetraders.api.Contract
	12, // 9: macgenius.spacetraders.api.DeliverContractResponse.Data.cargo:type_name -> macgenius.spacetraders.api.ShipCargo
	11, // 10: macgenius.spacetraders.api.FulFillContractResponse.Data.agent:type_name -> macgenius.spacetraders.api.Agent
	9,  // 11: macgenius.spacetraders.api.FulFillContractResponse.Data.contract:type_name -> macgenius.spacetraders.api.Contract
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_contracts_proto_init() }
func file_api_contracts_proto_init() {
	if File_api_contracts_proto != nil {
		return
	}
	file_agent_proto_init()
	file_contract_proto_init()
	file_meta_proto_init()
	file_ship_cargo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_contracts_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptContractResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_contracts_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeliverContractRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_contracts_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeliverContractResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_contracts_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FulFillContractResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_contracts_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetContractResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_contracts_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListContractsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_contracts_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptContractResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_contracts_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeliverContractResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_contracts_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FulFillContractResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_contracts_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_contracts_proto_goTypes,
		DependencyIndexes: file_api_contracts_proto_depIdxs,
		MessageInfos:      file_api_contracts_proto_msgTypes,
	}.Build()
	File_api_contracts_proto = out.File
	file_api_contracts_proto_rawDesc = nil
	file_api_contracts_proto_goTypes = nil
	file_api_contracts_proto_depIdxs = nil
}
