// SpaceTraders v2.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.2
// source: contract_type.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContractType int32

const (
	ContractType_PROCUREMENT ContractType = 0
	ContractType_TRANSPORT   ContractType = 1
	ContractType_SHUTTLE     ContractType = 2
)

// Enum value maps for ContractType.
var (
	ContractType_name = map[int32]string{
		0: "PROCUREMENT",
		1: "TRANSPORT",
		2: "SHUTTLE",
	}
	ContractType_value = map[string]int32{
		"PROCUREMENT": 0,
		"TRANSPORT":   1,
		"SHUTTLE":     2,
	}
)

func (x ContractType) Enum() *ContractType {
	p := new(ContractType)
	*p = x
	return p
}

func (x ContractType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContractType) Descriptor() protoreflect.EnumDescriptor {
	return file_contract_type_proto_enumTypes[0].Descriptor()
}

func (ContractType) Type() protoreflect.EnumType {
	return &file_contract_type_proto_enumTypes[0]
}

func (x ContractType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContractType.Descriptor instead.
func (ContractType) EnumDescriptor() ([]byte, []int) {
	return file_contract_type_proto_rawDescGZIP(), []int{0}
}

var File_contract_type_proto protoreflect.FileDescriptor

var file_contract_type_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x23, 0x6d, 0x61, 0x63, 0x67, 0x65, 0x6e, 0x69, 0x75, 0x73,
	0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2a, 0x3b, 0x0a, 0x0c, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x52,
	0x4f, 0x43, 0x55, 0x52, 0x45, 0x4d, 0x45, 0x4e, 0x54, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x54,
	0x52, 0x41, 0x4e, 0x53, 0x50, 0x4f, 0x52, 0x54, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x48,
	0x55, 0x54, 0x54, 0x4c, 0x45, 0x10, 0x02, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x69, 0x75, 0x73,
	0x2f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x70,
	0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_contract_type_proto_rawDescOnce sync.Once
	file_contract_type_proto_rawDescData = file_contract_type_proto_rawDesc
)

func file_contract_type_proto_rawDescGZIP() []byte {
	file_contract_type_proto_rawDescOnce.Do(func() {
		file_contract_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_contract_type_proto_rawDescData)
	})
	return file_contract_type_proto_rawDescData
}

var file_contract_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_contract_type_proto_goTypes = []interface{}{
	(ContractType)(0), // 0: macgenius.spacetraders.api.contract.ContractType
}
var file_contract_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contract_type_proto_init() }
func file_contract_type_proto_init() {
	if File_contract_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_contract_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contract_type_proto_goTypes,
		DependencyIndexes: file_contract_type_proto_depIdxs,
		EnumInfos:         file_contract_type_proto_enumTypes,
	}.Build()
	File_contract_type_proto = out.File
	file_contract_type_proto_rawDesc = nil
	file_contract_type_proto_goTypes = nil
	file_contract_type_proto_depIdxs = nil
}
