// SpaceTraders v2.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.2
// source: faction.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Faction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol       string          `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name         string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description  string          `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Headquarters string          `protobuf:"bytes,4,opt,name=headquarters,proto3" json:"headquarters,omitempty"`
	Traits       []*FactionTrait `protobuf:"bytes,5,rep,name=traits,proto3" json:"traits,omitempty"`
	IsRecruiting bool            `protobuf:"varint,6,opt,name=is_recruiting,json=isRecruiting,proto3" json:"is_recruiting,omitempty"` // Whether or not the faction is currently recruiting new agents.
}

func (x *Faction) Reset() {
	*x = Faction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_faction_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Faction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Faction) ProtoMessage() {}

func (x *Faction) ProtoReflect() protoreflect.Message {
	mi := &file_faction_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Faction.ProtoReflect.Descriptor instead.
func (*Faction) Descriptor() ([]byte, []int) {
	return file_faction_proto_rawDescGZIP(), []int{0}
}

func (x *Faction) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Faction) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Faction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Faction) GetHeadquarters() string {
	if x != nil {
		return x.Headquarters
	}
	return ""
}

func (x *Faction) GetTraits() []*FactionTrait {
	if x != nil {
		return x.Traits
	}
	return nil
}

func (x *Faction) GetIsRecruiting() bool {
	if x != nil {
		return x.IsRecruiting
	}
	return false
}

var File_faction_proto protoreflect.FileDescriptor

var file_faction_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x66, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x1a, 0x6d, 0x61, 0x63, 0x67, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x1a, 0x13, 0x66, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x72, 0x61, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xe2, 0x01, 0x0a, 0x07, 0x46, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79,
	0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x68, 0x65,
	0x61, 0x64, 0x71, 0x75, 0x61, 0x72, 0x74, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x68, 0x65, 0x61, 0x64, 0x71, 0x75, 0x61, 0x72, 0x74, 0x65, 0x72, 0x73, 0x12, 0x40,
	0x0a, 0x06, 0x74, 0x72, 0x61, 0x69, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28,
	0x2e, 0x6d, 0x61, 0x63, 0x67, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x72, 0x61, 0x69, 0x74, 0x52, 0x06, 0x74, 0x72, 0x61, 0x69, 0x74, 0x73,
	0x12, 0x23, 0x0a, 0x0d, 0x69, 0x73, 0x5f, 0x72, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x69, 0x6e,
	0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x69, 0x73, 0x52, 0x65, 0x63, 0x72, 0x75,
	0x69, 0x74, 0x69, 0x6e, 0x67, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x2f, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_faction_proto_rawDescOnce sync.Once
	file_faction_proto_rawDescData = file_faction_proto_rawDesc
)

func file_faction_proto_rawDescGZIP() []byte {
	file_faction_proto_rawDescOnce.Do(func() {
		file_faction_proto_rawDescData = protoimpl.X.CompressGZIP(file_faction_proto_rawDescData)
	})
	return file_faction_proto_rawDescData
}

var file_faction_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_faction_proto_goTypes = []interface{}{
	(*Faction)(nil),      // 0: macgenius.spacetraders.api.Faction
	(*FactionTrait)(nil), // 1: macgenius.spacetraders.api.FactionTrait
}
var file_faction_proto_depIdxs = []int32{
	1, // 0: macgenius.spacetraders.api.Faction.traits:type_name -> macgenius.spacetraders.api.FactionTrait
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_faction_proto_init() }
func file_faction_proto_init() {
	if File_faction_proto != nil {
		return
	}
	file_faction_trait_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_faction_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Faction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_faction_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_faction_proto_goTypes,
		DependencyIndexes: file_faction_proto_depIdxs,
		MessageInfos:      file_faction_proto_msgTypes,
	}.Build()
	File_faction_proto = out.File
	file_faction_proto_rawDesc = nil
	file_faction_proto_goTypes = nil
	file_faction_proto_depIdxs = nil
}
