// SpaceTraders v2.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.2
// source: market_transaction.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MarketTransactionType int32

const (
	MarketTransactionType_PURCHASE MarketTransactionType = 0
	MarketTransactionType_SELL     MarketTransactionType = 1
)

// Enum value maps for MarketTransactionType.
var (
	MarketTransactionType_name = map[int32]string{
		0: "PURCHASE",
		1: "SELL",
	}
	MarketTransactionType_value = map[string]int32{
		"PURCHASE": 0,
		"SELL":     1,
	}
)

func (x MarketTransactionType) Enum() *MarketTransactionType {
	p := new(MarketTransactionType)
	*p = x
	return p
}

func (x MarketTransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MarketTransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_market_transaction_proto_enumTypes[0].Descriptor()
}

func (MarketTransactionType) Type() protoreflect.EnumType {
	return &file_market_transaction_proto_enumTypes[0]
}

func (x MarketTransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MarketTransactionType.Descriptor instead.
func (MarketTransactionType) EnumDescriptor() ([]byte, []int) {
	return file_market_transaction_proto_rawDescGZIP(), []int{0}
}

type MarketTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WaypointSymbol string                 `protobuf:"bytes,1,opt,name=waypoint_symbol,json=waypointSymbol,proto3" json:"waypoint_symbol,omitempty"`              // The symbol of the waypoint where the transaction took place.
	ShipSymbol     string                 `protobuf:"bytes,2,opt,name=ship_symbol,json=shipSymbol,proto3" json:"ship_symbol,omitempty"`                          // The symbol of the ship that made the transaction.
	TradeSymbol    string                 `protobuf:"bytes,3,opt,name=trade_symbol,json=tradeSymbol,proto3" json:"trade_symbol,omitempty"`                       // The symbol of the trade good.
	Type           MarketTransactionType  `protobuf:"varint,4,opt,name=type,proto3,enum=macgenius.spacetraders.api.MarketTransactionType" json:"type,omitempty"` // The type of transaction.
	Units          int32                  `protobuf:"varint,5,opt,name=units,proto3" json:"units,omitempty"`                                                     // The number of units of the transaction.
	PricePerUnit   int32                  `protobuf:"varint,6,opt,name=price_per_unit,json=pricePerUnit,proto3" json:"price_per_unit,omitempty"`                 // The price per unit of the transaction.
	TotalPrice     int32                  `protobuf:"varint,7,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`                         // The total price of the transaction.
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                              // The timestamp of the transaction.
}

func (x *MarketTransaction) Reset() {
	*x = MarketTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_transaction_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarketTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketTransaction) ProtoMessage() {}

func (x *MarketTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_market_transaction_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketTransaction.ProtoReflect.Descriptor instead.
func (*MarketTransaction) Descriptor() ([]byte, []int) {
	return file_market_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *MarketTransaction) GetWaypointSymbol() string {
	if x != nil {
		return x.WaypointSymbol
	}
	return ""
}

func (x *MarketTransaction) GetShipSymbol() string {
	if x != nil {
		return x.ShipSymbol
	}
	return ""
}

func (x *MarketTransaction) GetTradeSymbol() string {
	if x != nil {
		return x.TradeSymbol
	}
	return ""
}

func (x *MarketTransaction) GetType() MarketTransactionType {
	if x != nil {
		return x.Type
	}
	return MarketTransactionType_PURCHASE
}

func (x *MarketTransaction) GetUnits() int32 {
	if x != nil {
		return x.Units
	}
	return 0
}

func (x *MarketTransaction) GetPricePerUnit() int32 {
	if x != nil {
		return x.PricePerUnit
	}
	return 0
}

func (x *MarketTransaction) GetTotalPrice() int32 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *MarketTransaction) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_market_transaction_proto protoreflect.FileDescriptor

var file_market_transaction_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x6d, 0x61, 0x63, 0x67,
	0x65, 0x6e, 0x69, 0x75, 0x73, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65,
	0x72, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xde, 0x02, 0x0a, 0x11, 0x4d, 0x61, 0x72, 0x6b,
	0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x0a,
	0x0f, 0x77, 0x61, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x77, 0x61, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x68, 0x69, 0x70, 0x5f, 0x73,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x68, 0x69,
	0x70, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x64, 0x65,
	0x5f, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74,
	0x72, 0x61, 0x64, 0x65, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x45, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x31, 0x2e, 0x6d, 0x61, 0x63, 0x67, 0x65,
	0x6e, 0x69, 0x75, 0x73, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x12, 0x24, 0x0a, 0x0e, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x5f, 0x70, 0x65, 0x72, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0c, 0x70, 0x72, 0x69, 0x63, 0x65, 0x50, 0x65, 0x72, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x38,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2a, 0x2f, 0x0a, 0x15, 0x4d, 0x61, 0x72, 0x6b,
	0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x55, 0x52, 0x43, 0x48, 0x41, 0x53, 0x45, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x53, 0x45, 0x4c, 0x4c, 0x10, 0x01, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x69,
	0x75, 0x73, 0x2f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2f,
	0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_market_transaction_proto_rawDescOnce sync.Once
	file_market_transaction_proto_rawDescData = file_market_transaction_proto_rawDesc
)

func file_market_transaction_proto_rawDescGZIP() []byte {
	file_market_transaction_proto_rawDescOnce.Do(func() {
		file_market_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(file_market_transaction_proto_rawDescData)
	})
	return file_market_transaction_proto_rawDescData
}

var file_market_transaction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_market_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_market_transaction_proto_goTypes = []interface{}{
	(MarketTransactionType)(0),    // 0: macgenius.spacetraders.api.MarketTransactionType
	(*MarketTransaction)(nil),     // 1: macgenius.spacetraders.api.MarketTransaction
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_market_transaction_proto_depIdxs = []int32{
	0, // 0: macgenius.spacetraders.api.MarketTransaction.type:type_name -> macgenius.spacetraders.api.MarketTransactionType
	2, // 1: macgenius.spacetraders.api.MarketTransaction.timestamp:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_market_transaction_proto_init() }
func file_market_transaction_proto_init() {
	if File_market_transaction_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_market_transaction_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarketTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_market_transaction_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_market_transaction_proto_goTypes,
		DependencyIndexes: file_market_transaction_proto_depIdxs,
		EnumInfos:         file_market_transaction_proto_enumTypes,
		MessageInfos:      file_market_transaction_proto_msgTypes,
	}.Build()
	File_market_transaction_proto = out.File
	file_market_transaction_proto_rawDesc = nil
	file_market_transaction_proto_goTypes = nil
	file_market_transaction_proto_depIdxs = nil
}
