// SpaceTraders v2.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.2
// source: market_trade_good.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MarketTradeGoodSupply int32

const (
	MarketTradeGoodSupply_SCARCE   MarketTradeGoodSupply = 0
	MarketTradeGoodSupply_LIMITED  MarketTradeGoodSupply = 1
	MarketTradeGoodSupply_MODERATE MarketTradeGoodSupply = 2
	MarketTradeGoodSupply_ABUNDANT MarketTradeGoodSupply = 3
)

// Enum value maps for MarketTradeGoodSupply.
var (
	MarketTradeGoodSupply_name = map[int32]string{
		0: "SCARCE",
		1: "LIMITED",
		2: "MODERATE",
		3: "ABUNDANT",
	}
	MarketTradeGoodSupply_value = map[string]int32{
		"SCARCE":   0,
		"LIMITED":  1,
		"MODERATE": 2,
		"ABUNDANT": 3,
	}
)

func (x MarketTradeGoodSupply) Enum() *MarketTradeGoodSupply {
	p := new(MarketTradeGoodSupply)
	*p = x
	return p
}

func (x MarketTradeGoodSupply) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MarketTradeGoodSupply) Descriptor() protoreflect.EnumDescriptor {
	return file_market_trade_good_proto_enumTypes[0].Descriptor()
}

func (MarketTradeGoodSupply) Type() protoreflect.EnumType {
	return &file_market_trade_good_proto_enumTypes[0]
}

func (x MarketTradeGoodSupply) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MarketTradeGoodSupply.Descriptor instead.
func (MarketTradeGoodSupply) EnumDescriptor() ([]byte, []int) {
	return file_market_trade_good_proto_rawDescGZIP(), []int{0}
}

type MarketTradeGood struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol        string                `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`                                                        // The symbol of the trade good.
	TradeVolume   int32                 `protobuf:"varint,2,opt,name=trade_volume,json=tradeVolume,proto3" json:"trade_volume,omitempty"`                          // The typical volume flowing through the market for this type of good. The larger the trade volume, the more stable prices will be.
	Supply        MarketTradeGoodSupply `protobuf:"varint,3,opt,name=supply,proto3,enum=macgenius.spacetraders.api.MarketTradeGoodSupply" json:"supply,omitempty"` // A rough estimate of the total supply of this good in the marketplace.
	PurchasePrice int32                 `protobuf:"varint,4,opt,name=purchase_price,json=purchasePrice,proto3" json:"purchase_price,omitempty"`                    // The price at which this good can be purchased from the market.
	SellPrice     int32                 `protobuf:"varint,5,opt,name=sell_price,json=sellPrice,proto3" json:"sell_price,omitempty"`                                // The price at which this good can be sold to the market.
}

func (x *MarketTradeGood) Reset() {
	*x = MarketTradeGood{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_trade_good_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarketTradeGood) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketTradeGood) ProtoMessage() {}

func (x *MarketTradeGood) ProtoReflect() protoreflect.Message {
	mi := &file_market_trade_good_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketTradeGood.ProtoReflect.Descriptor instead.
func (*MarketTradeGood) Descriptor() ([]byte, []int) {
	return file_market_trade_good_proto_rawDescGZIP(), []int{0}
}

func (x *MarketTradeGood) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *MarketTradeGood) GetTradeVolume() int32 {
	if x != nil {
		return x.TradeVolume
	}
	return 0
}

func (x *MarketTradeGood) GetSupply() MarketTradeGoodSupply {
	if x != nil {
		return x.Supply
	}
	return MarketTradeGoodSupply_SCARCE
}

func (x *MarketTradeGood) GetPurchasePrice() int32 {
	if x != nil {
		return x.PurchasePrice
	}
	return 0
}

func (x *MarketTradeGood) GetSellPrice() int32 {
	if x != nil {
		return x.SellPrice
	}
	return 0
}

var File_market_trade_good_proto protoreflect.FileDescriptor

var file_market_trade_good_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x5f, 0x74, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x67,
	0x6f, 0x6f, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x6d, 0x61, 0x63, 0x67, 0x65,
	0x6e, 0x69, 0x75, 0x73, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x2e, 0x61, 0x70, 0x69, 0x22, 0xdd, 0x01, 0x0a, 0x0f, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74,
	0x54, 0x72, 0x61, 0x64, 0x65, 0x47, 0x6f, 0x6f, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d,
	0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f,
	0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x76, 0x6f, 0x6c, 0x75, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x64, 0x65, 0x56, 0x6f,
	0x6c, 0x75, 0x6d, 0x65, 0x12, 0x49, 0x0a, 0x06, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x31, 0x2e, 0x6d, 0x61, 0x63, 0x67, 0x65, 0x6e, 0x69, 0x75, 0x73,
	0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x54, 0x72, 0x61, 0x64, 0x65, 0x47, 0x6f, 0x6f,
	0x64, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x52, 0x06, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x12,
	0x25, 0x0a, 0x0e, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x5f, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73,
	0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x6c, 0x6c, 0x5f, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x65, 0x6c, 0x6c,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x2a, 0x4c, 0x0a, 0x15, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x54,
	0x72, 0x61, 0x64, 0x65, 0x47, 0x6f, 0x6f, 0x64, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x12, 0x0a,
	0x0a, 0x06, 0x53, 0x43, 0x41, 0x52, 0x43, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x4c, 0x49,
	0x4d, 0x49, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x4f, 0x44, 0x45, 0x52,
	0x41, 0x54, 0x45, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x42, 0x55, 0x4e, 0x44, 0x41, 0x4e,
	0x54, 0x10, 0x03, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6d, 0x61, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x2f, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_market_trade_good_proto_rawDescOnce sync.Once
	file_market_trade_good_proto_rawDescData = file_market_trade_good_proto_rawDesc
)

func file_market_trade_good_proto_rawDescGZIP() []byte {
	file_market_trade_good_proto_rawDescOnce.Do(func() {
		file_market_trade_good_proto_rawDescData = protoimpl.X.CompressGZIP(file_market_trade_good_proto_rawDescData)
	})
	return file_market_trade_good_proto_rawDescData
}

var file_market_trade_good_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_market_trade_good_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_market_trade_good_proto_goTypes = []interface{}{
	(MarketTradeGoodSupply)(0), // 0: macgenius.spacetraders.api.MarketTradeGoodSupply
	(*MarketTradeGood)(nil),    // 1: macgenius.spacetraders.api.MarketTradeGood
}
var file_market_trade_good_proto_depIdxs = []int32{
	0, // 0: macgenius.spacetraders.api.MarketTradeGood.supply:type_name -> macgenius.spacetraders.api.MarketTradeGoodSupply
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_market_trade_good_proto_init() }
func file_market_trade_good_proto_init() {
	if File_market_trade_good_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_market_trade_good_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarketTradeGood); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_market_trade_good_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_market_trade_good_proto_goTypes,
		DependencyIndexes: file_market_trade_good_proto_depIdxs,
		EnumInfos:         file_market_trade_good_proto_enumTypes,
		MessageInfos:      file_market_trade_good_proto_msgTypes,
	}.Build()
	File_market_trade_good_proto = out.File
	file_market_trade_good_proto_rawDesc = nil
	file_market_trade_good_proto_goTypes = nil
	file_market_trade_good_proto_depIdxs = nil
}
