// SpaceTraders v2.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.2
// source: scanned_system.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScannedSystem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol       string     `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	SectorSymbol string     `protobuf:"bytes,2,opt,name=sector_symbol,json=sectorSymbol,proto3" json:"sector_symbol,omitempty"`
	Type         SystemType `protobuf:"varint,3,opt,name=type,proto3,enum=macgenius.spacetraders.api.sys.SystemType" json:"type,omitempty"`
	X            int32      `protobuf:"varint,4,opt,name=x,proto3" json:"x,omitempty"`
	Y            int32      `protobuf:"varint,5,opt,name=y,proto3" json:"y,omitempty"`
	Distance     int32      `protobuf:"varint,6,opt,name=distance,proto3" json:"distance,omitempty"`
}

func (x *ScannedSystem) Reset() {
	*x = ScannedSystem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scanned_system_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScannedSystem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScannedSystem) ProtoMessage() {}

func (x *ScannedSystem) ProtoReflect() protoreflect.Message {
	mi := &file_scanned_system_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScannedSystem.ProtoReflect.Descriptor instead.
func (*ScannedSystem) Descriptor() ([]byte, []int) {
	return file_scanned_system_proto_rawDescGZIP(), []int{0}
}

func (x *ScannedSystem) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ScannedSystem) GetSectorSymbol() string {
	if x != nil {
		return x.SectorSymbol
	}
	return ""
}

func (x *ScannedSystem) GetType() SystemType {
	if x != nil {
		return x.Type
	}
	return SystemType_NEUTRON_STAR
}

func (x *ScannedSystem) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ScannedSystem) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ScannedSystem) GetDistance() int32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

var File_scanned_system_proto protoreflect.FileDescriptor

var file_scanned_system_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x6d, 0x61, 0x63, 0x67, 0x65, 0x6e, 0x69, 0x75,
	0x73, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x61,
	0x70, 0x69, 0x1a, 0x11, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc4, 0x01, 0x0a, 0x0d, 0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65,
	0x64, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12,
	0x23, 0x0a, 0x0d, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x79,
	0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x3e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x2a, 0x2e, 0x6d, 0x61, 0x63, 0x67, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x2e, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x73, 0x79, 0x73, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79,
	0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x42, 0x28, 0x5a, 0x26,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x63, 0x2d, 0x67,
	0x65, 0x6e, 0x69, 0x75, 0x73, 0x2f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65,
	0x72, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_scanned_system_proto_rawDescOnce sync.Once
	file_scanned_system_proto_rawDescData = file_scanned_system_proto_rawDesc
)

func file_scanned_system_proto_rawDescGZIP() []byte {
	file_scanned_system_proto_rawDescOnce.Do(func() {
		file_scanned_system_proto_rawDescData = protoimpl.X.CompressGZIP(file_scanned_system_proto_rawDescData)
	})
	return file_scanned_system_proto_rawDescData
}

var file_scanned_system_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_scanned_system_proto_goTypes = []interface{}{
	(*ScannedSystem)(nil), // 0: macgenius.spacetraders.api.ScannedSystem
	(SystemType)(0),       // 1: macgenius.spacetraders.api.sys.SystemType
}
var file_scanned_system_proto_depIdxs = []int32{
	1, // 0: macgenius.spacetraders.api.ScannedSystem.type:type_name -> macgenius.spacetraders.api.sys.SystemType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_scanned_system_proto_init() }
func file_scanned_system_proto_init() {
	if File_scanned_system_proto != nil {
		return
	}
	file_system_type_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_scanned_system_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScannedSystem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_scanned_system_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scanned_system_proto_goTypes,
		DependencyIndexes: file_scanned_system_proto_depIdxs,
		MessageInfos:      file_scanned_system_proto_msgTypes,
	}.Build()
	File_scanned_system_proto = out.File
	file_scanned_system_proto_rawDesc = nil
	file_scanned_system_proto_goTypes = nil
	file_scanned_system_proto_depIdxs = nil
}
