// SpaceTraders v2.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.2
// source: ship_fuel.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShipFuelConsumed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount    int32                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`      // The amount of fuel consumed by the most recent transit or action.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // The time at which the fuel was consumed.
}

func (x *ShipFuelConsumed) Reset() {
	*x = ShipFuelConsumed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ship_fuel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShipFuelConsumed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipFuelConsumed) ProtoMessage() {}

func (x *ShipFuelConsumed) ProtoReflect() protoreflect.Message {
	mi := &file_ship_fuel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipFuelConsumed.ProtoReflect.Descriptor instead.
func (*ShipFuelConsumed) Descriptor() ([]byte, []int) {
	return file_ship_fuel_proto_rawDescGZIP(), []int{0}
}

func (x *ShipFuelConsumed) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ShipFuelConsumed) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Details of the ship's fuel tanks including how much fuel was consumed during the last transit or action.
type ShipFuel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Current  int32             `protobuf:"varint,1,opt,name=current,proto3" json:"current,omitempty"`   // The current amount of fuel in the ship's tanks.
	Capacity int32             `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"` // The maximum amount of fuel the ship's tanks can hold.
	Consumed *ShipFuelConsumed `protobuf:"bytes,3,opt,name=consumed,proto3" json:"consumed,omitempty"`
}

func (x *ShipFuel) Reset() {
	*x = ShipFuel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ship_fuel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShipFuel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipFuel) ProtoMessage() {}

func (x *ShipFuel) ProtoReflect() protoreflect.Message {
	mi := &file_ship_fuel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipFuel.ProtoReflect.Descriptor instead.
func (*ShipFuel) Descriptor() ([]byte, []int) {
	return file_ship_fuel_proto_rawDescGZIP(), []int{1}
}

func (x *ShipFuel) GetCurrent() int32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *ShipFuel) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *ShipFuel) GetConsumed() *ShipFuelConsumed {
	if x != nil {
		return x.Consumed
	}
	return nil
}

var File_ship_fuel_proto protoreflect.FileDescriptor

var file_ship_fuel_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x68, 0x69, 0x70, 0x5f, 0x66, 0x75, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x1a, 0x6d, 0x61, 0x63, 0x67, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x2e, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x64,
	0x0a, 0x10, 0x53, 0x68, 0x69, 0x70, 0x46, 0x75, 0x65, 0x6c, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d,
	0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x22, 0x8a, 0x01, 0x0a, 0x08, 0x53, 0x68, 0x69, 0x70, 0x46, 0x75, 0x65,
	0x6c, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63,
	0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x12, 0x48, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x73, 0x75,
	0x6d, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x6d, 0x61, 0x63, 0x67,
	0x65, 0x6e, 0x69, 0x75, 0x73, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65,
	0x72, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x68, 0x69, 0x70, 0x46, 0x75, 0x65, 0x6c, 0x43,
	0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x64, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65,
	0x64, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6d, 0x61, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x2f, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_ship_fuel_proto_rawDescOnce sync.Once
	file_ship_fuel_proto_rawDescData = file_ship_fuel_proto_rawDesc
)

func file_ship_fuel_proto_rawDescGZIP() []byte {
	file_ship_fuel_proto_rawDescOnce.Do(func() {
		file_ship_fuel_proto_rawDescData = protoimpl.X.CompressGZIP(file_ship_fuel_proto_rawDescData)
	})
	return file_ship_fuel_proto_rawDescData
}

var file_ship_fuel_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ship_fuel_proto_goTypes = []interface{}{
	(*ShipFuelConsumed)(nil),      // 0: macgenius.spacetraders.api.ShipFuelConsumed
	(*ShipFuel)(nil),              // 1: macgenius.spacetraders.api.ShipFuel
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_ship_fuel_proto_depIdxs = []int32{
	2, // 0: macgenius.spacetraders.api.ShipFuelConsumed.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: macgenius.spacetraders.api.ShipFuel.consumed:type_name -> macgenius.spacetraders.api.ShipFuelConsumed
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ship_fuel_proto_init() }
func file_ship_fuel_proto_init() {
	if File_ship_fuel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ship_fuel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShipFuelConsumed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ship_fuel_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShipFuel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ship_fuel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ship_fuel_proto_goTypes,
		DependencyIndexes: file_ship_fuel_proto_depIdxs,
		MessageInfos:      file_ship_fuel_proto_msgTypes,
	}.Build()
	File_ship_fuel_proto = out.File
	file_ship_fuel_proto_rawDesc = nil
	file_ship_fuel_proto_goTypes = nil
	file_ship_fuel_proto_depIdxs = nil
}
