// SpaceTraders v2.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.2
// source: ship_crew.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShipCrewRotation int32

const (
	ShipCrewRotation_STRICT  ShipCrewRotation = 0
	ShipCrewRotation_RELAXED ShipCrewRotation = 1
)

// Enum value maps for ShipCrewRotation.
var (
	ShipCrewRotation_name = map[int32]string{
		0: "STRICT",
		1: "RELAXED",
	}
	ShipCrewRotation_value = map[string]int32{
		"STRICT":  0,
		"RELAXED": 1,
	}
)

func (x ShipCrewRotation) Enum() *ShipCrewRotation {
	p := new(ShipCrewRotation)
	*p = x
	return p
}

func (x ShipCrewRotation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShipCrewRotation) Descriptor() protoreflect.EnumDescriptor {
	return file_ship_crew_proto_enumTypes[0].Descriptor()
}

func (ShipCrewRotation) Type() protoreflect.EnumType {
	return &file_ship_crew_proto_enumTypes[0]
}

func (x ShipCrewRotation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShipCrewRotation.Descriptor instead.
func (ShipCrewRotation) EnumDescriptor() ([]byte, []int) {
	return file_ship_crew_proto_rawDescGZIP(), []int{0}
}

// The ship's crew service and maintain the ship's systems and equipment.
type ShipCrew struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Current  int32            `protobuf:"varint,1,opt,name=current,proto3" json:"current,omitempty"`                                                    // The current number of crew members on the ship.
	Required int32            `protobuf:"varint,2,opt,name=required,proto3" json:"required,omitempty"`                                                  // The minimum number of crew members required to maintain the ship.
	Capacity int32            `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`                                                  // The maximum number of crew members the ship can support.
	Rotation ShipCrewRotation `protobuf:"varint,4,opt,name=rotation,proto3,enum=macgenius.spacetraders.api.ShipCrewRotation" json:"rotation,omitempty"` // The rotation of crew shifts. A stricter shift improves the ship's performance. A more relaxed shift improves the crew's morale.
	Morale   int32            `protobuf:"varint,5,opt,name=morale,proto3" json:"morale,omitempty"`                                                      // A rough measure of the crew's morale. A higher morale means the crew is happier and more productive. A lower morale means the ship is more prone to accidents. [0, 100]
	Wages    int32            `protobuf:"varint,6,opt,name=wages,proto3" json:"wages,omitempty"`                                                        // The amount of credits per crew member paid per hour. Wages are paid when a ship docks at a civilized waypoint. [0, ∞)
}

func (x *ShipCrew) Reset() {
	*x = ShipCrew{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ship_crew_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShipCrew) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipCrew) ProtoMessage() {}

func (x *ShipCrew) ProtoReflect() protoreflect.Message {
	mi := &file_ship_crew_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipCrew.ProtoReflect.Descriptor instead.
func (*ShipCrew) Descriptor() ([]byte, []int) {
	return file_ship_crew_proto_rawDescGZIP(), []int{0}
}

func (x *ShipCrew) GetCurrent() int32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *ShipCrew) GetRequired() int32 {
	if x != nil {
		return x.Required
	}
	return 0
}

func (x *ShipCrew) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *ShipCrew) GetRotation() ShipCrewRotation {
	if x != nil {
		return x.Rotation
	}
	return ShipCrewRotation_STRICT
}

func (x *ShipCrew) GetMorale() int32 {
	if x != nil {
		return x.Morale
	}
	return 0
}

func (x *ShipCrew) GetWages() int32 {
	if x != nil {
		return x.Wages
	}
	return 0
}

var File_ship_crew_proto protoreflect.FileDescriptor

var file_ship_crew_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x68, 0x69, 0x70, 0x5f, 0x63, 0x72, 0x65, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x1a, 0x6d, 0x61, 0x63, 0x67, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x2e, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x22, 0xd4, 0x01,
	0x0a, 0x08, 0x53, 0x68, 0x69, 0x70, 0x43, 0x72, 0x65, 0x77, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x12, 0x48, 0x0a, 0x08,
	0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2c,
	0x2e, 0x6d, 0x61, 0x63, 0x67, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x68, 0x69, 0x70,
	0x43, 0x72, 0x65, 0x77, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x72, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x72, 0x61, 0x6c, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x6f, 0x72, 0x61, 0x6c, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x77, 0x61, 0x67, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77,
	0x61, 0x67, 0x65, 0x73, 0x2a, 0x2b, 0x0a, 0x10, 0x53, 0x68, 0x69, 0x70, 0x43, 0x72, 0x65, 0x77,
	0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x52, 0x49,
	0x43, 0x54, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x45, 0x4c, 0x41, 0x58, 0x45, 0x44, 0x10,
	0x01, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6d, 0x61, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x2f, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_ship_crew_proto_rawDescOnce sync.Once
	file_ship_crew_proto_rawDescData = file_ship_crew_proto_rawDesc
)

func file_ship_crew_proto_rawDescGZIP() []byte {
	file_ship_crew_proto_rawDescOnce.Do(func() {
		file_ship_crew_proto_rawDescData = protoimpl.X.CompressGZIP(file_ship_crew_proto_rawDescData)
	})
	return file_ship_crew_proto_rawDescData
}

var file_ship_crew_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ship_crew_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ship_crew_proto_goTypes = []interface{}{
	(ShipCrewRotation)(0), // 0: macgenius.spacetraders.api.ShipCrewRotation
	(*ShipCrew)(nil),      // 1: macgenius.spacetraders.api.ShipCrew
}
var file_ship_crew_proto_depIdxs = []int32{
	0, // 0: macgenius.spacetraders.api.ShipCrew.rotation:type_name -> macgenius.spacetraders.api.ShipCrewRotation
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ship_crew_proto_init() }
func file_ship_crew_proto_init() {
	if File_ship_crew_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ship_crew_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShipCrew); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ship_crew_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ship_crew_proto_goTypes,
		DependencyIndexes: file_ship_crew_proto_depIdxs,
		EnumInfos:         file_ship_crew_proto_enumTypes,
		MessageInfos:      file_ship_crew_proto_msgTypes,
	}.Build()
	File_ship_crew_proto = out.File
	file_ship_crew_proto_rawDesc = nil
	file_ship_crew_proto_goTypes = nil
	file_ship_crew_proto_depIdxs = nil
}
