// SpaceTraders v2.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.2
// source: ship_cargo.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShipCargo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Capacity  int32            `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`  // The max number of items that can be stored in the cargo hold.
	Units     int32            `protobuf:"varint,2,opt,name=units,proto3" json:"units,omitempty"`        // The number of items currently stored in the cargo hold.
	Inventory []*ShipCargoItem `protobuf:"bytes,3,rep,name=inventory,proto3" json:"inventory,omitempty"` // The items currently in the cargo hold.
}

func (x *ShipCargo) Reset() {
	*x = ShipCargo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ship_cargo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShipCargo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipCargo) ProtoMessage() {}

func (x *ShipCargo) ProtoReflect() protoreflect.Message {
	mi := &file_ship_cargo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipCargo.ProtoReflect.Descriptor instead.
func (*ShipCargo) Descriptor() ([]byte, []int) {
	return file_ship_cargo_proto_rawDescGZIP(), []int{0}
}

func (x *ShipCargo) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *ShipCargo) GetUnits() int32 {
	if x != nil {
		return x.Units
	}
	return 0
}

func (x *ShipCargo) GetInventory() []*ShipCargoItem {
	if x != nil {
		return x.Inventory
	}
	return nil
}

var File_ship_cargo_proto protoreflect.FileDescriptor

var file_ship_cargo_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x68, 0x69, 0x70, 0x5f, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x1a, 0x6d, 0x61, 0x63, 0x67, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x2e, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x1a, 0x15,
	0x73, 0x68, 0x69, 0x70, 0x5f, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x86, 0x01, 0x0a, 0x09, 0x53, 0x68, 0x69, 0x70, 0x43, 0x61,
	0x72, 0x67, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x75, 0x6e, 0x69, 0x74, 0x73, 0x12, 0x47, 0x0a, 0x09, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f,
	0x72, 0x79, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x6d, 0x61, 0x63, 0x67, 0x65,
	0x6e, 0x69, 0x75, 0x73, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x68, 0x69, 0x70, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x09, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x42, 0x28,
	0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x63,
	0x2d, 0x67, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x2f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61,
	0x64, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ship_cargo_proto_rawDescOnce sync.Once
	file_ship_cargo_proto_rawDescData = file_ship_cargo_proto_rawDesc
)

func file_ship_cargo_proto_rawDescGZIP() []byte {
	file_ship_cargo_proto_rawDescOnce.Do(func() {
		file_ship_cargo_proto_rawDescData = protoimpl.X.CompressGZIP(file_ship_cargo_proto_rawDescData)
	})
	return file_ship_cargo_proto_rawDescData
}

var file_ship_cargo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ship_cargo_proto_goTypes = []interface{}{
	(*ShipCargo)(nil),     // 0: macgenius.spacetraders.api.ShipCargo
	(*ShipCargoItem)(nil), // 1: macgenius.spacetraders.api.ShipCargoItem
}
var file_ship_cargo_proto_depIdxs = []int32{
	1, // 0: macgenius.spacetraders.api.ShipCargo.inventory:type_name -> macgenius.spacetraders.api.ShipCargoItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ship_cargo_proto_init() }
func file_ship_cargo_proto_init() {
	if File_ship_cargo_proto != nil {
		return
	}
	file_ship_cargo_item_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ship_cargo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShipCargo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ship_cargo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ship_cargo_proto_goTypes,
		DependencyIndexes: file_ship_cargo_proto_depIdxs,
		MessageInfos:      file_ship_cargo_proto_msgTypes,
	}.Build()
	File_ship_cargo_proto = out.File
	file_ship_cargo_proto_rawDesc = nil
	file_ship_cargo_proto_goTypes = nil
	file_ship_cargo_proto_depIdxs = nil
}
