// SpaceTraders v2.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.2
// source: ship_requirements.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The requirements for installation on a ship.
type ShipRequirements struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Power int32 `protobuf:"varint,1,opt,name=power,proto3" json:"power,omitempty"` // The amount of power required from the reactor.
	Crew  int32 `protobuf:"varint,2,opt,name=crew,proto3" json:"crew,omitempty"`   // The number of crew required for operation.
	Slots int32 `protobuf:"varint,3,opt,name=slots,proto3" json:"slots,omitempty"` // The number of module slots required for installation.
}

func (x *ShipRequirements) Reset() {
	*x = ShipRequirements{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ship_requirements_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShipRequirements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipRequirements) ProtoMessage() {}

func (x *ShipRequirements) ProtoReflect() protoreflect.Message {
	mi := &file_ship_requirements_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipRequirements.ProtoReflect.Descriptor instead.
func (*ShipRequirements) Descriptor() ([]byte, []int) {
	return file_ship_requirements_proto_rawDescGZIP(), []int{0}
}

func (x *ShipRequirements) GetPower() int32 {
	if x != nil {
		return x.Power
	}
	return 0
}

func (x *ShipRequirements) GetCrew() int32 {
	if x != nil {
		return x.Crew
	}
	return 0
}

func (x *ShipRequirements) GetSlots() int32 {
	if x != nil {
		return x.Slots
	}
	return 0
}

var File_ship_requirements_proto protoreflect.FileDescriptor

var file_ship_requirements_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x68, 0x69, 0x70, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x6d, 0x61, 0x63, 0x67, 0x65,
	0x6e, 0x69, 0x75, 0x73, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x2e, 0x61, 0x70, 0x69, 0x22, 0x52, 0x0a, 0x10, 0x53, 0x68, 0x69, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6f, 0x77,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x72, 0x65, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x72, 0x65, 0x77, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x69,
	0x75, 0x73, 0x2f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2f,
	0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ship_requirements_proto_rawDescOnce sync.Once
	file_ship_requirements_proto_rawDescData = file_ship_requirements_proto_rawDesc
)

func file_ship_requirements_proto_rawDescGZIP() []byte {
	file_ship_requirements_proto_rawDescOnce.Do(func() {
		file_ship_requirements_proto_rawDescData = protoimpl.X.CompressGZIP(file_ship_requirements_proto_rawDescData)
	})
	return file_ship_requirements_proto_rawDescData
}

var file_ship_requirements_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ship_requirements_proto_goTypes = []interface{}{
	(*ShipRequirements)(nil), // 0: macgenius.spacetraders.api.ShipRequirements
}
var file_ship_requirements_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ship_requirements_proto_init() }
func file_ship_requirements_proto_init() {
	if File_ship_requirements_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ship_requirements_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShipRequirements); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ship_requirements_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ship_requirements_proto_goTypes,
		DependencyIndexes: file_ship_requirements_proto_depIdxs,
		MessageInfos:      file_ship_requirements_proto_msgTypes,
	}.Build()
	File_ship_requirements_proto = out.File
	file_ship_requirements_proto_rawDesc = nil
	file_ship_requirements_proto_goTypes = nil
	file_ship_requirements_proto_depIdxs = nil
}
