// SpaceTraders v2.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.2
// source: survey_deposit.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A surveyed deposit of a mineral or resource available for extraction.
type SurveyDeposit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"` // The symbol of the deposit.
}

func (x *SurveyDeposit) Reset() {
	*x = SurveyDeposit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_survey_deposit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SurveyDeposit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SurveyDeposit) ProtoMessage() {}

func (x *SurveyDeposit) ProtoReflect() protoreflect.Message {
	mi := &file_survey_deposit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SurveyDeposit.ProtoReflect.Descriptor instead.
func (*SurveyDeposit) Descriptor() ([]byte, []int) {
	return file_survey_deposit_proto_rawDescGZIP(), []int{0}
}

func (x *SurveyDeposit) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

var File_survey_deposit_proto protoreflect.FileDescriptor

var file_survey_deposit_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x75, 0x72, 0x76, 0x65, 0x79, 0x5f, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x6d, 0x61, 0x63, 0x67, 0x65, 0x6e, 0x69, 0x75,
	0x73, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x61,
	0x70, 0x69, 0x22, 0x27, 0x0a, 0x0d, 0x53, 0x75, 0x72, 0x76, 0x65, 0x79, 0x44, 0x65, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x42, 0x28, 0x5a, 0x26, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x63, 0x2d, 0x67, 0x65,
	0x6e, 0x69, 0x75, 0x73, 0x2f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_survey_deposit_proto_rawDescOnce sync.Once
	file_survey_deposit_proto_rawDescData = file_survey_deposit_proto_rawDesc
)

func file_survey_deposit_proto_rawDescGZIP() []byte {
	file_survey_deposit_proto_rawDescOnce.Do(func() {
		file_survey_deposit_proto_rawDescData = protoimpl.X.CompressGZIP(file_survey_deposit_proto_rawDescData)
	})
	return file_survey_deposit_proto_rawDescData
}

var file_survey_deposit_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_survey_deposit_proto_goTypes = []interface{}{
	(*SurveyDeposit)(nil), // 0: macgenius.spacetraders.api.SurveyDeposit
}
var file_survey_deposit_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_survey_deposit_proto_init() }
func file_survey_deposit_proto_init() {
	if File_survey_deposit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_survey_deposit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SurveyDeposit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_survey_deposit_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_survey_deposit_proto_goTypes,
		DependencyIndexes: file_survey_deposit_proto_depIdxs,
		MessageInfos:      file_survey_deposit_proto_msgTypes,
	}.Build()
	File_survey_deposit_proto = out.File
	file_survey_deposit_proto_rawDesc = nil
	file_survey_deposit_proto_goTypes = nil
	file_survey_deposit_proto_depIdxs = nil
}
