// SpaceTraders v2.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.2
// source: survey_size.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SurveySize int32

const (
	SurveySize_SMALL    SurveySize = 0
	SurveySize_MODERATE SurveySize = 1
	SurveySize_LARGE    SurveySize = 2
)

// Enum value maps for SurveySize.
var (
	SurveySize_name = map[int32]string{
		0: "SMALL",
		1: "MODERATE",
		2: "LARGE",
	}
	SurveySize_value = map[string]int32{
		"SMALL":    0,
		"MODERATE": 1,
		"LARGE":    2,
	}
)

func (x SurveySize) Enum() *SurveySize {
	p := new(SurveySize)
	*p = x
	return p
}

func (x SurveySize) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SurveySize) Descriptor() protoreflect.EnumDescriptor {
	return file_survey_size_proto_enumTypes[0].Descriptor()
}

func (SurveySize) Type() protoreflect.EnumType {
	return &file_survey_size_proto_enumTypes[0]
}

func (x SurveySize) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SurveySize.Descriptor instead.
func (SurveySize) EnumDescriptor() ([]byte, []int) {
	return file_survey_size_proto_rawDescGZIP(), []int{0}
}

var File_survey_size_proto protoreflect.FileDescriptor

var file_survey_size_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x75, 0x72, 0x76, 0x65, 0x79, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x21, 0x6d, 0x61, 0x63, 0x67, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x2e, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x73, 0x75, 0x72, 0x76, 0x65, 0x79, 0x2a, 0x30, 0x0a, 0x0a, 0x53, 0x75, 0x72, 0x76, 0x65, 0x79,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x4d, 0x41, 0x4c, 0x4c, 0x10, 0x00, 0x12,
	0x0c, 0x0a, 0x08, 0x4d, 0x4f, 0x44, 0x45, 0x52, 0x41, 0x54, 0x45, 0x10, 0x01, 0x12, 0x09, 0x0a,
	0x05, 0x4c, 0x41, 0x52, 0x47, 0x45, 0x10, 0x02, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x69, 0x75,
	0x73, 0x2f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2f, 0x61,
	0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_survey_size_proto_rawDescOnce sync.Once
	file_survey_size_proto_rawDescData = file_survey_size_proto_rawDesc
)

func file_survey_size_proto_rawDescGZIP() []byte {
	file_survey_size_proto_rawDescOnce.Do(func() {
		file_survey_size_proto_rawDescData = protoimpl.X.CompressGZIP(file_survey_size_proto_rawDescData)
	})
	return file_survey_size_proto_rawDescData
}

var file_survey_size_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_survey_size_proto_goTypes = []interface{}{
	(SurveySize)(0), // 0: macgenius.spacetraders.api.survey.SurveySize
}
var file_survey_size_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_survey_size_proto_init() }
func file_survey_size_proto_init() {
	if File_survey_size_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_survey_size_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_survey_size_proto_goTypes,
		DependencyIndexes: file_survey_size_proto_depIdxs,
		EnumInfos:         file_survey_size_proto_enumTypes,
	}.Build()
	File_survey_size_proto = out.File
	file_survey_size_proto_rawDesc = nil
	file_survey_size_proto_goTypes = nil
	file_survey_size_proto_depIdxs = nil
}
