// SpaceTraders v2.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.2
// source: system_type.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SystemType int32

const (
	SystemType_NEUTRON_STAR SystemType = 0
	SystemType_RED_STAR     SystemType = 1
	SystemType_ORANGE_STAR  SystemType = 2
	SystemType_BLUE_STAR    SystemType = 3
	SystemType_YOUNG_STAR   SystemType = 4
	SystemType_WHITE_DWARF  SystemType = 5
	SystemType_BLACK_HOLE   SystemType = 6
	SystemType_HYPERGIANT   SystemType = 7
	SystemType_NEBULA       SystemType = 8
	SystemType_UNSTABLE     SystemType = 9
)

// Enum value maps for SystemType.
var (
	SystemType_name = map[int32]string{
		0: "NEUTRON_STAR",
		1: "RED_STAR",
		2: "ORANGE_STAR",
		3: "BLUE_STAR",
		4: "YOUNG_STAR",
		5: "WHITE_DWARF",
		6: "BLACK_HOLE",
		7: "HYPERGIANT",
		8: "NEBULA",
		9: "UNSTABLE",
	}
	SystemType_value = map[string]int32{
		"NEUTRON_STAR": 0,
		"RED_STAR":     1,
		"ORANGE_STAR":  2,
		"BLUE_STAR":    3,
		"YOUNG_STAR":   4,
		"WHITE_DWARF":  5,
		"BLACK_HOLE":   6,
		"HYPERGIANT":   7,
		"NEBULA":       8,
		"UNSTABLE":     9,
	}
)

func (x SystemType) Enum() *SystemType {
	p := new(SystemType)
	*p = x
	return p
}

func (x SystemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SystemType) Descriptor() protoreflect.EnumDescriptor {
	return file_system_type_proto_enumTypes[0].Descriptor()
}

func (SystemType) Type() protoreflect.EnumType {
	return &file_system_type_proto_enumTypes[0]
}

func (x SystemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SystemType.Descriptor instead.
func (SystemType) EnumDescriptor() ([]byte, []int) {
	return file_system_type_proto_rawDescGZIP(), []int{0}
}

var File_system_type_proto protoreflect.FileDescriptor

var file_system_type_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x1e, 0x6d, 0x61, 0x63, 0x67, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x2e, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x73, 0x79, 0x73, 0x2a, 0xa7, 0x01, 0x0a, 0x0a, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x4e, 0x45, 0x55, 0x54, 0x52, 0x4f, 0x4e, 0x5f, 0x53, 0x54,
	0x41, 0x52, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x52,
	0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x4f, 0x52, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x53, 0x54, 0x41,
	0x52, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x42, 0x4c, 0x55, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x52,
	0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x59, 0x4f, 0x55, 0x4e, 0x47, 0x5f, 0x53, 0x54, 0x41, 0x52,
	0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b, 0x57, 0x48, 0x49, 0x54, 0x45, 0x5f, 0x44, 0x57, 0x41, 0x52,
	0x46, 0x10, 0x05, 0x12, 0x0e, 0x0a, 0x0a, 0x42, 0x4c, 0x41, 0x43, 0x4b, 0x5f, 0x48, 0x4f, 0x4c,
	0x45, 0x10, 0x06, 0x12, 0x0e, 0x0a, 0x0a, 0x48, 0x59, 0x50, 0x45, 0x52, 0x47, 0x49, 0x41, 0x4e,
	0x54, 0x10, 0x07, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x45, 0x42, 0x55, 0x4c, 0x41, 0x10, 0x08, 0x12,
	0x0c, 0x0a, 0x08, 0x55, 0x4e, 0x53, 0x54, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x09, 0x42, 0x28, 0x5a,
	0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x63, 0x2d,
	0x67, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x2f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64,
	0x65, 0x72, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_system_type_proto_rawDescOnce sync.Once
	file_system_type_proto_rawDescData = file_system_type_proto_rawDesc
)

func file_system_type_proto_rawDescGZIP() []byte {
	file_system_type_proto_rawDescOnce.Do(func() {
		file_system_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_system_type_proto_rawDescData)
	})
	return file_system_type_proto_rawDescData
}

var file_system_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_system_type_proto_goTypes = []interface{}{
	(SystemType)(0), // 0: macgenius.spacetraders.api.sys.SystemType
}
var file_system_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_system_type_proto_init() }
func file_system_type_proto_init() {
	if File_system_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_system_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_system_type_proto_goTypes,
		DependencyIndexes: file_system_type_proto_depIdxs,
		EnumInfos:         file_system_type_proto_enumTypes,
	}.Build()
	File_system_type_proto = out.File
	file_system_type_proto_rawDesc = nil
	file_system_type_proto_goTypes = nil
	file_system_type_proto_depIdxs = nil
}
