// SpaceTraders v2.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.2
// source: waypoint_type.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WaypointType int32

const (
	WaypointType_PLANET          WaypointType = 0
	WaypointType_GAS_GIANT       WaypointType = 1
	WaypointType_MOON            WaypointType = 2
	WaypointType_ORBITAL_STATION WaypointType = 3
	WaypointType_JUMP_GATE       WaypointType = 4
	WaypointType_ASTEROID_FIELD  WaypointType = 5
	WaypointType_NEBULA          WaypointType = 6
	WaypointType_DEBRIS_FIELD    WaypointType = 7
	WaypointType_GRAVITY_WELL    WaypointType = 8
)

// Enum value maps for WaypointType.
var (
	WaypointType_name = map[int32]string{
		0: "PLANET",
		1: "GAS_GIANT",
		2: "MOON",
		3: "ORBITAL_STATION",
		4: "JUMP_GATE",
		5: "ASTEROID_FIELD",
		6: "NEBULA",
		7: "DEBRIS_FIELD",
		8: "GRAVITY_WELL",
	}
	WaypointType_value = map[string]int32{
		"PLANET":          0,
		"GAS_GIANT":       1,
		"MOON":            2,
		"ORBITAL_STATION": 3,
		"JUMP_GATE":       4,
		"ASTEROID_FIELD":  5,
		"NEBULA":          6,
		"DEBRIS_FIELD":    7,
		"GRAVITY_WELL":    8,
	}
)

func (x WaypointType) Enum() *WaypointType {
	p := new(WaypointType)
	*p = x
	return p
}

func (x WaypointType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WaypointType) Descriptor() protoreflect.EnumDescriptor {
	return file_waypoint_type_proto_enumTypes[0].Descriptor()
}

func (WaypointType) Type() protoreflect.EnumType {
	return &file_waypoint_type_proto_enumTypes[0]
}

func (x WaypointType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WaypointType.Descriptor instead.
func (WaypointType) EnumDescriptor() ([]byte, []int) {
	return file_waypoint_type_proto_rawDescGZIP(), []int{0}
}

var File_waypoint_type_proto protoreflect.FileDescriptor

var file_waypoint_type_proto_rawDesc = []byte{
	0x0a, 0x13, 0x77, 0x61, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x6d, 0x61, 0x63, 0x67, 0x65, 0x6e, 0x69, 0x75, 0x73,
	0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x77, 0x70, 0x2a, 0x9b, 0x01, 0x0a, 0x0c, 0x57, 0x61, 0x79, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x4c, 0x41, 0x4e, 0x45, 0x54, 0x10,
	0x00, 0x12, 0x0d, 0x0a, 0x09, 0x47, 0x41, 0x53, 0x5f, 0x47, 0x49, 0x41, 0x4e, 0x54, 0x10, 0x01,
	0x12, 0x08, 0x0a, 0x04, 0x4d, 0x4f, 0x4f, 0x4e, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x4f, 0x52,
	0x42, 0x49, 0x54, 0x41, 0x4c, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x03, 0x12,
	0x0d, 0x0a, 0x09, 0x4a, 0x55, 0x4d, 0x50, 0x5f, 0x47, 0x41, 0x54, 0x45, 0x10, 0x04, 0x12, 0x12,
	0x0a, 0x0e, 0x41, 0x53, 0x54, 0x45, 0x52, 0x4f, 0x49, 0x44, 0x5f, 0x46, 0x49, 0x45, 0x4c, 0x44,
	0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x45, 0x42, 0x55, 0x4c, 0x41, 0x10, 0x06, 0x12, 0x10,
	0x0a, 0x0c, 0x44, 0x45, 0x42, 0x52, 0x49, 0x53, 0x5f, 0x46, 0x49, 0x45, 0x4c, 0x44, 0x10, 0x07,
	0x12, 0x10, 0x0a, 0x0c, 0x47, 0x52, 0x41, 0x56, 0x49, 0x54, 0x59, 0x5f, 0x57, 0x45, 0x4c, 0x4c,
	0x10, 0x08, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6d, 0x61, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x2f, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_waypoint_type_proto_rawDescOnce sync.Once
	file_waypoint_type_proto_rawDescData = file_waypoint_type_proto_rawDesc
)

func file_waypoint_type_proto_rawDescGZIP() []byte {
	file_waypoint_type_proto_rawDescOnce.Do(func() {
		file_waypoint_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_waypoint_type_proto_rawDescData)
	})
	return file_waypoint_type_proto_rawDescData
}

var file_waypoint_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_waypoint_type_proto_goTypes = []interface{}{
	(WaypointType)(0), // 0: macgenius.spacetraders.api.wp.WaypointType
}
var file_waypoint_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_waypoint_type_proto_init() }
func file_waypoint_type_proto_init() {
	if File_waypoint_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_waypoint_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_waypoint_type_proto_goTypes,
		DependencyIndexes: file_waypoint_type_proto_depIdxs,
		EnumInfos:         file_waypoint_type_proto_enumTypes,
	}.Build()
	File_waypoint_type_proto = out.File
	file_waypoint_type_proto_rawDesc = nil
	file_waypoint_type_proto_goTypes = nil
	file_waypoint_type_proto_depIdxs = nil
}
